# Generated by Django 3.2 on 2022-01-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complete', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='stripe_pid',
        ),
        migrations.AddField(
            model_name='booking',
            name='more_information',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
