# Generated by Django 3.2 on 2022-01-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complete', '0003_alter_booking_more_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='more_information',
            field=models.TextField(blank=True, default=''),
        ),
    ]
