# Generated by Django 3.2 on 2022-01-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complete', '0004_alter_booking_more_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='more_information',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
