# Generated by Django 3.2 on 2022-01-30 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complete', '0005_alter_booking_more_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinglineitem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='complete.booking'),
        ),
    ]
