# Generated by Django 3.2 on 2022-02-02 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_has_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_colors',
        ),
    ]
